/*
 *    MCreator note:
 *
 *    If you lock base mod element files, you can edit this file and the proxy files
 *    and they won't get overwritten. If you change your mod package or modid, you
 *    need to apply these changes to this file MANUALLY.
 *
 *    Settings in @Mod annotation WON'T be changed in case of the base mod element
 *    files lock too, so you need to set them manually here in such case.
 *
 *    Keep the ElementsLaCroix object in this class and all calls to this object
 *    INTACT in order to preserve functionality of mod elements generated by MCreator.
 *
 *    If you do not lock base mod element files in Workspace settings, this file
 *    will be REGENERATED on each build.
 *
 */
package net.whatamidoingstudios.lacroix;

import net.minecraft.block.Block;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.potion.Potion;
import net.minecraft.util.ResourceLocation;
import net.minecraft.world.biome.Biome;
import net.minecraftforge.advancements.critereon.ItemPredicates;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.capabilities.Capability;
import net.minecraftforge.common.capabilities.CapabilityInject;
import net.minecraftforge.common.capabilities.CapabilityManager;
import net.minecraftforge.event.AttachCapabilitiesEvent;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.gameevent.TickEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import net.whatamidoingstudios.lacroix.advancements.HealtierThanSodaPredicate;
import net.whatamidoingstudios.lacroix.block.LaCroixGuiHandler;
import net.whatamidoingstudios.lacroix.block.heater.BlockHeater;
import net.whatamidoingstudios.lacroix.block.heater.TileEntityHeater;
import net.whatamidoingstudios.lacroix.item.ItemAdvancedUpgrade;
import net.whatamidoingstudios.lacroix.item.ItemAppleCranberryLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemApricotLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemBerryLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemBlackberryCucumberLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemBlockHeater;
import net.whatamidoingstudios.lacroix.item.ItemCherryLimeLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemCoconutLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemCranberryRaspberryLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemExcellentUpgrade;
import net.whatamidoingstudios.lacroix.item.ItemKeylimeLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemKiwiWatermelonLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemLaColaLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemLemonLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemLimeLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemMangoLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemMelonGrapefruitLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemOrangeLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemPamplemousseLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemPassionfruitLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemPeachPearLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemPerfectUpgrade;
import net.whatamidoingstudios.lacroix.item.ItemPineappleLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemPureLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemStrawberryLaCroix;
import net.whatamidoingstudios.lacroix.item.ItemTangerineLaCroix;
import net.whatamidoingstudios.lacroix.network.LaCroixNetworkHandler;

@Mod(modid = LaCroix.MODID, version = LaCroix.VERSION)
public class LaCroix {
	public static final String MODID = "lacroix";
	public static final String VERSION = "1.0.0";
	
	@SidedProxy(clientSide = "net.whatamidoingstudios.lacroix.ClientProxyLaCroix", serverSide = "net.whatamidoingstudios.lacroix.ServerProxyLaCroix")
	public static IProxyLaCroix proxy;
	
	@Mod.Instance(MODID)
	public static LaCroix instance;
	
	public static LaCroixNetworkHandler networkHandler = new LaCroixNetworkHandler();
	
	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(this);
		NetworkRegistry.INSTANCE.registerGuiHandler(this, new LaCroixGuiHandler());
		ItemPredicates.register(new ResourceLocation(MODID, "healthierthansoda"), HealtierThanSodaPredicate::new);
		proxy.preInit(event);
	}
	
	@Mod.EventHandler
	public void init(FMLInitializationEvent event) {
		proxy.init(event);
	}

	@Mod.EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		proxy.postInit(event);
	}

	@Mod.EventHandler
	public void serverLoad(FMLServerStartingEvent event) {
		proxy.serverLoad(event);
	}

	@SubscribeEvent
	public void registerBlocks(RegistryEvent.Register<Block> event) {
		event.getRegistry().registerAll(
				new BlockHeater()
		);
		GameRegistry.registerTileEntity(TileEntityHeater.class, "lacroix:heatertileentity");
	}

	@SubscribeEvent
	public void registerItems(RegistryEvent.Register<Item> event) {
		event.getRegistry().registerAll(
			new ItemAppleCranberryLaCroix(),
			new ItemApricotLaCroix(),
			new ItemBerryLaCroix(),
			new ItemBlackberryCucumberLaCroix(),
			new ItemCherryLimeLaCroix(),
			new ItemCoconutLaCroix(),
			new ItemCranberryRaspberryLaCroix(),
			new ItemKeylimeLaCroix(),
			new ItemKiwiWatermelonLaCroix(),
			new ItemLaColaLaCroix(),
			new ItemLemonLaCroix(),
			new ItemLimeLaCroix(),
			new ItemMangoLaCroix(),
			new ItemMelonGrapefruitLaCroix(),
			new ItemOrangeLaCroix(),
			new ItemPamplemousseLaCroix(),
			new ItemPassionfruitLaCroix(),
			new ItemPeachPearLaCroix(),
			new ItemPineappleLaCroix(),
			new ItemPureLaCroix(),
			new ItemStrawberryLaCroix(),
			new ItemTangerineLaCroix(),
			new ItemAdvancedUpgrade(),
			new ItemExcellentUpgrade(),
			new ItemPerfectUpgrade(),
			new ItemBlockHeater()
		);
	}
	
	@SubscribeEvent
	public void registerBiomes(RegistryEvent.Register<Biome> event) {

	}

	@SubscribeEvent
	public void registerEntities(RegistryEvent.Register<EntityEntry> event) {

	}

	@SubscribeEvent
	public void registerPotions(RegistryEvent.Register<Potion> event) {

	}

	@SubscribeEvent
	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {

	}
	
	@SubscribeEvent
	@SideOnly(Side.CLIENT)
	public void registerModels(ModelRegistryEvent event) {
		ModelLoader.setCustomModelResourceLocation(ModObjects.applecranberrylacroix, 0, new ModelResourceLocation(ModObjects.applecranberrylacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.apricotlacroix, 0, new ModelResourceLocation(ModObjects.apricotlacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.coconutlacroix, 0, new ModelResourceLocation(ModObjects.coconutlacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.peachpearlacroix, 0, new ModelResourceLocation(ModObjects.peachpearlacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.pineapplelacroix, 0, new ModelResourceLocation(ModObjects.pineapplelacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.tangerinelacroix, 0, new ModelResourceLocation(ModObjects.tangerinelacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.cherrylimelacroix, 0, new ModelResourceLocation(ModObjects.cherrylimelacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.limelacroix, 0, new ModelResourceLocation(ModObjects.limelacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.keylimelacroix, 0, new ModelResourceLocation(ModObjects.keylimelacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.berrylacroix, 0, new ModelResourceLocation(ModObjects.berrylacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.cranberryraspberrylacroix, 0, new ModelResourceLocation(ModObjects.cranberryraspberrylacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.orangelacroix, 0, new ModelResourceLocation(ModObjects.orangelacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.blackberrycucumberlacroix, 0, new ModelResourceLocation(ModObjects.blackberrycucumberlacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.purelacroix, 0, new ModelResourceLocation(ModObjects.purelacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.lacolalacroix, 0, new ModelResourceLocation(ModObjects.lacolalacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.passionfruitlacroix, 0, new ModelResourceLocation(ModObjects.passionfruitlacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.pamplemousselacroix, 0, new ModelResourceLocation(ModObjects.pamplemousselacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.mangolacroix, 0, new ModelResourceLocation(ModObjects.mangolacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.melongrapefruitlacroix, 0, new ModelResourceLocation(ModObjects.melongrapefruitlacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.strawberrylacroix, 0, new ModelResourceLocation(ModObjects.strawberrylacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.kiwiwatermelonlacroix, 0, new ModelResourceLocation(ModObjects.kiwiwatermelonlacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.lemonlacroix, 0, new ModelResourceLocation(ModObjects.lemonlacroix.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.advancedupgrade, 0, new ModelResourceLocation(ModObjects.advancedupgrade.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.excellentupgrade, 0, new ModelResourceLocation(ModObjects.excellentupgrade.getRegistryName(), "inventory"));
		ModelLoader.setCustomModelResourceLocation(ModObjects.perfectupgrade, 0, new ModelResourceLocation(ModObjects.perfectupgrade.getRegistryName(), "inventory"));
		ModObjects.itemblock_coalheater.initModels();
	}
}
